INSERT INTO now_focus (type, badge_en, badge_id, title_en, title_id, desc_en, desc_id, meta_label_en, meta_label_id, meta_value_en, meta_value_id, items_en, items_id, sort_order) VALUES
('project', 'In Progress', 'Sedang Berjalan', 'Current Project', 'Proyek Saat Ini', 'Building a multi-tenant SaaS infrastructure platform with automated provisioning, real-time monitoring dashboards, and zero-downtime deployment pipelines.', 'Membangun platform infrastruktur SaaS multi-tenant dengan provisi otomatis, dashboard monitoring real-time, dan pipeline deployment tanpa downtime.', 'Impact', 'Dampak', 'Serves 50+ enterprise clients. Reduces deployment time by 70%.', 'Melayani 50+ klien enterprise. Mengurangi waktu deployment sebesar 70%.', '["Node.js", "Kubernetes", "Terraform", "Prometheus", "React"]'::jsonb, '["Node.js", "Kubernetes", "Terraform", "Prometheus", "React"]'::jsonb, 1),

('learning', 'Exploring', 'Eksplorasi', 'Learning & R&D', 'Pembelajaran & R&D', 'Diving deep into AI/ML Ops patterns, LLM integration architectures, and platform engineering best practices for high-scale systems.', 'Mendalami pola AI/ML Ops, arsitektur integrasi LLM, dan praktik terbaik platform engineering untuk sistem berskala besar.', NULL, NULL, NULL, NULL, '["LLMOps & AI Infrastructure", "Platform Engineering Patterns", "eBPF for Network Observability", "Rust for Systems Programming"]'::jsonb, '["LLMOps & Infrastruktur AI", "Pola Platform Engineering", "eBPF untuk Observabilitas Jaringan", "Rust untuk Pemrograman Sistem"]'::jsonb, 2),

('reading', 'In Progress', 'Sedang Berjalan', 'Reading & Certifications', 'Membaca & Sertifikasi', 'Structured learning track focused on cloud architecture and engineering leadership for senior-level growth.', 'Jalur pembelajaran terstruktur yang berfokus pada arsitektur cloud dan kepemimpinan rekayasa untuk pertumbuhan level senior.', NULL, NULL, NULL, NULL, '["📘 | AWS Solutions Architect Pro | Certification", "📗 | Designing Data-Intensive Applications | Book", "🎓 | Engineering Management Fundamentals | Course"]'::jsonb, '["📘 | AWS Solutions Architect Pro | Sertifikasi", "📗 | Designing Data-Intensive Applications | Buku", "🎓 | Engineering Management Fundamentals | Kursus"]'::jsonb, 3),

('milestone', 'Shipped', 'Selesai', NULL, NULL, 'Migrated core monolith to event-driven microservices architecture on Kubernetes', 'Migrasi monolith inti ke arsitektur microservices berbasis event di Kubernetes', 'June 2026', 'Juni 2026', NULL, NULL, '["Kubernetes", "gRPC", "Kafka"]'::jsonb, '["Kubernetes", "gRPC", "Kafka"]'::jsonb, 4),

('milestone', 'Shipped', 'Selesai', NULL, NULL, 'Led a cross-functional team of 5 engineers through Alpha release of naralink platform', 'Memimpin tim lintas fungsi 5 engineer melalui rilis Alpha platform naralink', 'May 2026', 'Mei 2026', NULL, NULL, '["Leadership", "Agile"]'::jsonb, '["Leadership", "Agile"]'::jsonb, 5),

('milestone', 'Shipped', 'Selesai', NULL, NULL, 'Implemented AI-powered anomaly detection reducing incident response time by 60%', 'Mengimplementasikan deteksi anomali berbasis AI yang mengurangi waktu respons insiden sebesar 60%', 'Apr 2026', 'Apr 2026', NULL, NULL, '["AI/ML", "Python", "Prometheus"]'::jsonb, '["AI/ML", "Python", "Prometheus"]'::jsonb, 6),

('milestone', 'In Progress', 'Sedang Berjalan', NULL, NULL, 'Enrolled in AWS Solutions Architect Professional certification path', 'Mendaftar jalur sertifikasi AWS Solutions Architect Professional', 'Mar 2026', 'Mar 2026', NULL, NULL, '["AWS", "Cloud Architecture"]'::jsonb, '["AWS", "Arsitektur Cloud"]'::jsonb, 7),

('milestone', 'Shipped', 'Selesai', NULL, NULL, 'Designed and deployed zero-trust network architecture for enterprise client infrastructure', 'Merancang dan menerapkan arsitektur jaringan zero-trust untuk infrastruktur klien enterprise', 'Feb 2026', 'Feb 2026', NULL, NULL, '["Security", "Zero Trust", "VPN"]'::jsonb, '["Keamanan", "Zero Trust", "VPN"]'::jsonb, 8);
